In [1]:
import requests
import json 
import ta
import tensorflow as tf
import keras
from sklearn.utils.class_weight import compute_class_weight
from pathlib import Path
from matplotlib import pyplot as plt
import time
import datetime
from datetime import timezone
import urllib
from datetime import timedelta
import h5py
from urllib import parse
import pprint
import dateutil
import concurrent.futures as fut
import numpy as np
from keras import layers
import pandas as pd
import mplfinance
import csv
import ccxt

In [25]:
path_f15=Path(r'D:\Python1\AI\cripto_bot\from_3_3.feather')
path_f4=Path(r'D:\Python1\AI\cripto_bot\from_2_3.feather')
path_f1=Path(r'D:\Python1\AI\cripto_bot\from_1_3.feather')
pd.DataFrame([]).to_feather(path_f15)
pd.DataFrame([]).to_feather(path_f4)
pd.DataFrame([]).to_feather(path_f1)

pd.DataFrame([])

sd=pd.read_parquet(r'D:\Python1\AI\cripto_bot\from_3_3.parquet')
sd.iloc[:10]

,timestamp,open,high,low,close,volue,rsi,adx,bb,atr
27,2018-12-10 06:45:00+00:00,3488.21,3500.00,3485.02,3496.79,323.685620,30.713288,13.326928,0.070247,19.865462
28,2018-12-10 07:00:00+00:00,3495.54,3497.93,3478.58,3480.54,486.309949,26.733885,14.756340,-0.012167,19.828644
29,2018-12-10 07:15:00+00:00,3482.30,3495.62,3475.00,3490.01,409.948754,32.243530,16.213944,0.128488,19.885169
30,2018-12-10 07:30:00+00:00,3490.01,3519.00,3488.00,3512.54,557.239411,43.189304,16.009288,0.354710,20.679086
31,2018-12-10 07:45:00+00:00,3512.54,3523.98,3498.80,3503.63,335.683598,40.409103,15.530216,0.292587,21.000579
32,2018-12-10 08:00:00+00:00,3503.63,3513.63,3491.91,3494.06,370.442375,37.608781,15.412551,0.232010,21.051967
33,2018-12-10 08:15:00+00:00,3495.08,3500.02,3486.30,3497.13,292.613621,39.067557,15.564146,0.283070,20.528255
34,2018-12-10 08:30:00+00:00,3496.51,3505.76,3495.00,3498.98,202.448053,39.978290,15.330132,0.320438,19.830522
35,2018-12-10 08:45:00+00:00,3498.24,3499.96,3491.01,3491.77,205.537704,37.618402,15.315433,0.275963,19.053342
36,2018-12-10 09:00:00+00:00,3491.36,3493.17,3460.37,3471.78,802.599778,31.981635,16.580987,0.129162,20.035246

In [2]:
path15=r'D:\Python1\AI\cripto_bot\from_3_3.parquet'
path4=r"D:\Python1\AI\cripto_bot\from_2_3.parquet"
path1=r"D:\Python1\AI\cripto_bot\from_1_3.parquet"

class add_i():
    def __init__(self):
        self.columns=['timestamp','open','high','low','close','volue']

    def __call__(self,m15,fr):
                
        m15_pd=pd.DataFrame(m15,columns=self.columns)
        rsi=ta.momentum.rsi(m15_pd['close'],14)
        print(f'fr:{fr}| len:{len(m15_pd)}')
        try:
            adx=ta.trend.adx(m15_pd['high'],m15_pd['low'],m15_pd['close'],14)
        except Exception as a:
            print(a,'| ', m15_pd,"|",fr)
        bb=ta.volatility.BollingerBands(m15_pd['close'],20,2)
        bolban=bb.bollinger_pband()
        atr=ta.volatility.average_true_range(m15_pd['high'],m15_pd['low'],m15_pd['close'])
        #добавление данных
        m15_pd['rsi']=rsi
        m15_pd['adx']=adx
        m15_pd['bb']=bolban
        #m15_pd['obv']=obv
        m15_pd['atr']=atr

                
        m15_pd['timestamp']=pd.to_datetime(m15_pd['timestamp'],utc=True,unit='ms')
        start=m15_pd["timestamp"].iloc[29]

        end=m15_pd['timestamp'][len(m15_pd['timestamp'])-1]
        print(f'start:{start}')

        print(f"end:{end}")

        m15_pd=m15_pd.iloc[29:]
        #разбиение на этап

        return m15_pd

In [3]:
ki=ccxt.binance()
ku=ccxt.kucoin()
path15=r'D:\Python1\AI\cripto_bot\from_3_3.parquet'
path15_=r'D:\Python1\AI\cripto_bot\from_3_4.parquet'

path4=r"D:\Python1\AI\cripto_bot\from_2_3.parquet"
path4_=r"D:\Python1\AI\cripto_bot\from_2_4.parquet"

path1=r"D:\Python1\AI\cripto_bot\from_1_3.parquet"
path1_=r"D:\Python1\AI\cripto_bot\from_1_4.parquet"

path_f15=Path(r'D:\Python1\AI\cripto_bot\from_3_3.feather')
path_f4=Path(r'D:\Python1\AI\cripto_bot\from_2_3.feather')
path_f1=Path(r'D:\Python1\AI\cripto_bot\from_1_3.feather')

class parse():
    def __init__(self):
        self.data15=pd.read_parquet(path15_,engine='pyarrow')
        self.data4=pd.read_parquet(path4_,engine='pyarrow')
        self.data1=pd.read_parquet(path1_,engine='pyarrow')

        self.data15_f=pd.read_feather(path_f15)
        self.data4_f=pd.read_feather(path_f4)
        self.data1_f=pd.read_feather(path_f1)
            
        self.timeframe=['1w','4h','15m']
        self.add_indikator=add_i()
        print('11')

    def __call__(self,t):
        
        if self.data15_f.empty:
            last_=self.data15['timestamp'].iloc[-1]
            print(last_,'1')
        else:
            last_=self.data15_f['timestamp'].iloc[-1]
            print(last_,'2')

        data={}
        if t-last_>=timedelta(minutes=15):
            po=True
        #if t-datetime.datetime.fromisoformat("2021-02-11T02:45:00+00:00")>=timedelta(minutes=15):
            start=(self.data15['timestamp'].iloc[-1]+datetime.timedelta(minutes=30))
           

            #start=datetime.datetime.fromisoformat("2021-02-11T03:15:00+00:00")
            end=t+timedelta(seconds=1)
            
            with fut.ThreadPoolExecutor(3) as tr:
                            future=[tr.submit(self.daa1,fr,start,end) for fr in self.timeframe]
                            #future=[tr.submit(self.daa1,self.timeframe[2],start,end),]  
                            for k in fut.as_completed(future):
                                    fr,u=k.result()
                                    data[fr]=u
                
        else:
            start_ind=len(self.data15)
            self.data15_f.index=range(start_ind,start_ind+len(self.data15_f))
            data['15m']=pd.concat([self.data15,self.data15_f])

            start_ind=len(self.data4)
            self.data4_f.index=range(start_ind,start_ind+len(self.data4_f))
            data['4h']=pd.concat([self.data4,self.data4_f])

            start_ind=len(self.data1)
            self.data1_f.index=range(start_ind,start_ind+len(self.data1_f))
            data['1w']=pd.concat([self.data1,self.data1_f])
            po=False
        return data,po
    def parsbi(self,start_,end_,fr):
        cans=[]
        since=start_
        while since<=end_:
            
            can=ki.fetch_ohlcv("BTC/USDT",fr,since,limit=1000)
            if not can:
                break
            c1=[c for c in can if c[0]<end_]
            if not c1:
                break
            cans.extend(c1)
            since = cans[-1][0] + 1  # Передвигаем `since` на последнюю свечу
            time.sleep(0.1) 
        return cans
    
    def daa1(self,fr,start,end):
        if fr=='15m':
             start1=start - timedelta(minutes=15*100)
             fun=self.test_data15
             start=start-timedelta(minutes=15*30)
             save=self.save15
        elif fr=='4h':
             start1=start-timedelta(hours=4*100)
             fun=self.test_data4
             start=start-timedelta(hours=4*30)
             save=self.save4
             
        elif fr=='1w':
             start1=start - timedelta(days=7*100)
             fun=self.test_data1
             start=start-timedelta(days=7*30)
             save=self.save1

        else:
             raise Exception('dont correct ft in daa1')
        print(f'fr:{fr}: start:{start1}| end:{end}')
        start_ku=ki.parse8601(start1.isoformat())
        end_ku=ki.parse8601(end.isoformat())
        u=self.parsbi(start_ku,end_ku,fr)
        u=fun(fr,u,start,end)
        u=self.add_indikator(u,fr)
        u=save(u)
        #for i in u:
             #print(f'{fr}:{datetime.datetime.fromtimestamp(i[0]/1000,timezone.utc)}')
        return fr,u
    
    def save15(self,data):
        self.data15_f=pd.concat([self.data15_f,data],ignore_index=True)
        self.data15_f=self.data15_f.drop_duplicates(subset='timestamp',keep='last')
        start_ind=len(self.data15)
        self.data15_f.index=range(start_ind,start_ind+len(self.data15_f))
        data_=pd.concat([self.data15,self.data15_f]).drop_duplicates(subset='timestamp',keep='last')

        if len(self.data15_f)>=16:
            self.data15=data_
            self.data15.to_parquet(path15_)
            self.data15_f=pd.DataFrame([])
        self.data15_f=self.data15_f
        self.data15_f.to_feather(path_f15)
        return data_
    
    def save4(self,data):
        self.data4_f=pd.concat([self.data4_f,data],ignore_index=True)
        self.data4_f=self.data4_f.drop_duplicates(subset='timestamp',keep='last')
        start_ind=len(self.data4)
        self.data4_f.index=range(start_ind,start_ind+len(self.data4_f))
        data_=pd.concat([self.data4,self.data4_f]).drop_duplicates(subset='timestamp',keep='last')
        
        if len(self.data4_f)>=16:
            self.data4=data_
            
            self.data4.to_parquet(path4_)
            self.data4_f=pd.DataFrame([])
        self.data4_f.to_feather(path_f4)
        return data_
        

    def save1(self,data):
        self.data1_f=pd.concat([self.data1_f,data],ignore_index=True)
        self.data1_f=self.data1_f.drop_duplicates(subset='timestamp',keep='last')
        start_ind=len(self.data1)
        self.data1_f.index=range(start_ind,start_ind+len(self.data1_f))
        data_=pd.concat([self.data1,self.data1_f]).drop_duplicates(subset='timestamp',keep='last')
        if len(self.data1_f)>=10:
            self.data1=data_
            self.data1.to_parquet(path1_)
            self.data1_f=pd.DataFrame([])
        self.data1_f.to_feather(path_f1)
        return data_



    def parsku(self,start_,end_,timeframe):
        cans=[]
        since=start_
        while since<=end_:
            can=ku.fetch_ohlcv("BTC/USDT",timeframe,since,limit=1000)
            if not can:
                break
            c1=[c for c in can if c[0]<end_]
            if not c1:
                break
            cans.extend(c1)
            since = cans[-1][0] + 1  # Передвигаем `since` на последнюю свечу 
        return cans

    def test_data15(self,timeframe,data,start,end):
        m15=data
        dot=[]
        last=datetime.datetime.fromtimestamp(m15[0][0]/1000,datetime.timezone.utc)
        print(f'last:{last}-end:{datetime.datetime.fromtimestamp(m15[-1][0]/1000,datetime.timezone.utc)}')
        for ind,i in enumerate(m15):
        #if 10<ind<20:
         #    print(datetime.datetime.fromtimestamp(m15[ind][0]/1000,timezone.utc))
            if datetime.datetime.fromtimestamp(i[0]/1000,timezone.utc) < start:
                last=datetime.datetime.fromtimestamp(i[0]/1000,datetime.timezone.utc)
                continue
            if ind ==0:
                continue
            if datetime.datetime.fromtimestamp(i[0]/1000,datetime.timezone.utc)-datetime.timedelta(minutes=15)!=last:
                print('--------------------------')
                start=last
                print(f'start1:{start.isoformat()}',end='|')
                end=datetime.datetime.fromtimestamp(i[0]/1000,datetime.timezone.utc)-datetime.timedelta(seconds=1)
                print(f'end1:{end.isoformat()}',end='|')
                print(f"i:{datetime.datetime.fromtimestamp(i[0]/1000,datetime.timezone.utc)}| last:{last}")

                start_ku_v=ku.parse8601((start-datetime.timedelta(minutes=15*99)).isoformat())
                end_ku_v=ku.parse8601(end.isoformat())
                #print('start ku:',(last-datetime.timedelta(hours=4*175)))
                #print('end ku:',last)
                #print(f'time:{datetime.datetime.fromtimestamp(m15[ind][0]/1000,timezone.utc)} | ind:{ind} | last time:{datetime.datetime.fromtimestamp(m15[ind-1][0]/1000,timezone.utc)} | time:{last}')
                #print('start bi:',datetime.datetime.fromtimestamp( dat[-175][0]/1000,timezone.utc))
                #print('end bi:',datetime.datetime.fromtimestamp(dat[-1][0]/1000,timezone.utc))
                ku_can_v=self.parsku(start_ku_v,end_ku_v,timeframe)

                start1=datetime.datetime.fromtimestamp(ku_can_v[0][0]/1000,timezone.utc)
                
                for o in ku_can_v:
                    if datetime.datetime.fromtimestamp(o[0]/1000,timezone.utc)!=start1:
                        print(f"ERROR({datetime.datetime.fromtimestamp(o[0]/1000,timezone.utc)} : {start1})")
                        start1=datetime.datetime.fromtimestamp(o[0]/1000,timezone.utc)
                    start1+=datetime.timedelta(minutes=15)
                mean_v1=np.array(data[:100])
                pl=datetime.datetime.fromtimestamp(mean_v1[-1][0]/1000,timezone.utc)
                for o in range(1,len(mean_v1)):
                    o+=1
                    o*=-1
                    if pl-datetime.timedelta(minutes=15)!=datetime.datetime.fromtimestamp(mean_v1[o][0]/1000,timezone.utc):
                        print("AAAA:",o,'|',datetime.datetime.fromtimestamp(mean_v1[o][0]/1000,timezone.utc))

                    pl=datetime.datetime.fromtimestamp(mean_v1[o][0]/1000,timezone.utc)
                mean_v1=mean_v1[:,-1]
                mean_v2=np.array(ku_can_v)[:100,-1]
                
                
                #mean_v2=mean_v2[mean_v2!=0]
                #print('v1 start:',datetime.datetime.fromtimestamp(mean_v1[0][0]/1000,timezone.utc),' | end:',datetime.datetime.fromtimestamp(mean_v1[-1][0]/1000,timezone.utc),'| len:',len(mean_v1))
                #print('v2 start:',datetime.datetime.fromtimestamp(mean_v2[0][0]/1000,timezone.utc),' | end:',datetime.datetime.fromtimestamp(mean_v2[-1][0]/1000,timezone.utc),'| len:',len(mean_v2))
                
                k=mean_v1/mean_v2
                #print("v1:",mean_v1[:5],"| v2:",mean_v2[:5])
                k=k[k!=np.inf].mean()
                #print('k not normaliz:',k,end='|')
                k=k
                
                #print('k:',k)
                #print('norm:',(mean_v2*k)[:10])
                
                # start_ku=ku.parse8601(start.isoformat())
                # end_ku=ku.parse8601(end.isoformat())

                # ku_can=self.parsku(start_ku,end_ku,timeframe)
                ku_can=ku_can_v[100:]
                #print(f'len:{len(ku_can)}')
                #try:
                    #print(f'strt:{datetime.datetime.fromtimestamp(ku_can[0][0]/1000,datetime.timezone.utc)}')
                    #print(f'end:{datetime.datetime.fromtimestamp(ku_can[-1][0]/1000,datetime.timezone.utc)}')
                #except IndexError:
                    #print(int((end-start).total_seconds()))
                    #'''for kline in range(int((end-start).total_seconds()/)):
                     #   print(kline)'''
                #timestamps = [c[0] for c in m15]  # Получаем список всех timestamp
                ku_can_new=[]
                for inde,o in enumerate(ku_can):
                    if inde==0:
                        o[1]=data[-1][4]
                        o[2]=max(o[2],max(o[4],o[1]))
                        o[3]=min(o[3],min(o[4],o[1]))
                    if inde+1==len(ku_can):
                        o[4]=i[1]
                        o[2]=max(o[2],max(o[4],o[1]))
                        o[3]=min(o[3],min(o[4],o[1]))
                    o[5]=o[5]*k
                    ku_can_new.append(o)
                
                #print('last close:',m15[-1][4],' new open:',ku_can_new[0][1],'| new close:',ku_can_new[-1][4],' last open:',i[1])
                ku_can=ku_can_new
                dot.extend(ku_can)
                dot.append(i)

            #da['15m']['15m']
            #for candle in ku_can:
            #    if candle[0] not in timestamps:
            #        index = bisect.bisect_right(timestamps, candle[0])  # Найти правильное место
            #        m15.insert(index, candle)
            
            
                '''
                
                ge=requests.get('https://api.kucoin.com/api/v1/market/candles',params)
                ge.raise_for_status()
                print(f'strt:{datetime.datetime.fromtimestamp(ge[0][0])}')
                print(f'end:{datetime.datetime.fromtimestamp(ge[-1][6])}')
                #?symbol=BTC-USDT&type=1hour&startAt=1679616000&endAt=1679702400
                
                '''

            else:
                dot.append(i)
            last=datetime.datetime.fromtimestamp(i[0]/1000,datetime.timezone.utc)
        return dot


    def test_data4(self,timeframe,data,start,end):
        m15=data
        dot=[]
        last=datetime.datetime.fromtimestamp(m15[0][0]/1000,datetime.timezone.utc)
        for ind,i in enumerate(m15):

            if datetime.datetime.fromtimestamp(i[0]/1000,timezone.utc) < start:
                last=datetime.datetime.fromtimestamp(i[0]/1000,datetime.timezone.utc)
                continue
            if ind ==0:
                continue
            if datetime.datetime.fromtimestamp(i[0]/1000,datetime.timezone.utc)-datetime.timedelta(hours=4)!=last:
                print('--------------------------')
                start=last
                print(f'start1:{start.isoformat()}',end='|')
                end=datetime.datetime.fromtimestamp(i[0]/1000,datetime.timezone.utc)-datetime.timedelta(seconds=1)
                print(f'end1:{end.isoformat()}',end='|')
                print(f"i:{datetime.datetime.fromtimestamp(i[0]/1000,datetime.timezone.utc)}| last:{last}")

                start_ku_v=ku.parse8601((start-datetime.timedelta(hours=4*99)).isoformat())
                end_ku_v=ku.parse8601(end.isoformat())

                ku_can_v=self.parsku(start_ku_v,end_ku_v,timeframe)

                start1=datetime.datetime.fromtimestamp(ku_can_v[0][0]/1000,timezone.utc)

                for o in ku_can_v:
                    if datetime.datetime.fromtimestamp(o[0]/1000,timezone.utc)!=start1:
                        print(f"ERROR({datetime.datetime.fromtimestamp(o[0]/1000,timezone.utc)} : {start1})")
                        start1=datetime.datetime.fromtimestamp(o[0]/1000,timezone.utc)
                    start1+=datetime.timedelta(hours=4)
                mean_v1=np.array(data[:100])
                pl=datetime.datetime.fromtimestamp(mean_v1[-1][0]/1000,timezone.utc)
                for o in range(1,len(mean_v1)):
                    o+=1
                    o*=-1
                    if pl-datetime.timedelta(hours=4)!=datetime.datetime.fromtimestamp(mean_v1[o][0]/1000,timezone.utc):
                        print("AAAA:",o,'|',datetime.datetime.fromtimestamp(mean_v1[o][0]/1000,timezone.utc))

                    pl=datetime.datetime.fromtimestamp(mean_v1[o][0]/1000,timezone.utc)
                mean_v1=mean_v1[:,-1]
                mean_v2=np.array(ku_can_v)[:100,-1]

                k=mean_v1/mean_v2
                k=k[k!=np.inf].mean()
                ku_can=ku_can_v[100:]
                ku_can_new=[]
                for inde,o in enumerate(ku_can):
                    if inde==0:
                        o[1]=data[-1][4]
                        o[2]=max(o[2],max(o[4],o[1]))
                        o[3]=min(o[3],min(o[4],o[1]))
                    if inde+1==len(ku_can):
                        o[4]=i[1]
                        o[2]=max(o[2],max(o[4],o[1]))
                        o[3]=min(o[3],min(o[4],o[1]))
                    o[5]=o[5]*k
                    ku_can_new.append(o)

                ku_can=ku_can_new
                dot.extend(ku_can)
                dot.append(i)

            else:
                dot.append(i)
            last=datetime.datetime.fromtimestamp(i[0]/1000,datetime.timezone.utc)
        return dot
    
    def test_data1(self,timeframe,data,start,end):
        m15=data
        dot=[]
        last=datetime.datetime.fromtimestamp(m15[0][0]/1000,datetime.timezone.utc)
        for ind,i in enumerate(m15):

            if datetime.datetime.fromtimestamp(i[0]/1000,timezone.utc) < start:
                last=datetime.datetime.fromtimestamp(i[0]/1000,datetime.timezone.utc)
                continue
            if ind ==0:
                continue
            if datetime.datetime.fromtimestamp(i[0]/1000,datetime.timezone.utc)-datetime.timedelta(days=7)!=last:
                print('--------------------------')
                start=last
                print(f'start1:{start.isoformat()}',end='|')
                end=datetime.datetime.fromtimestamp(i[0]/1000,datetime.timezone.utc)-datetime.timedelta(seconds=1)
                print(f'end1:{end.isoformat()}',end='|')
                print(f"i:{datetime.datetime.fromtimestamp(i[0]/1000,datetime.timezone.utc)}| last:{last}")

                start_ku_v=ku.parse8601((start-datetime.timedelta(days=7*99)).isoformat())
                end_ku_v=ku.parse8601(end.isoformat())

                ku_can_v=self.parsku(start_ku_v,end_ku_v,timeframe)

                start1=datetime.datetime.fromtimestamp(ku_can_v[0][0]/1000,timezone.utc)

                for o in ku_can_v:
                    if datetime.datetime.fromtimestamp(o[0]/1000,timezone.utc)!=start1:
                        print(f"ERROR({datetime.datetime.fromtimestamp(o[0]/1000,timezone.utc)} : {start1})")
                        start1=datetime.datetime.fromtimestamp(o[0]/1000,timezone.utc)
                    start1+=datetime.timedelta(days=7)
                mean_v1=np.array(data[:100])
                pl=datetime.datetime.fromtimestamp(mean_v1[-1][0]/1000,timezone.utc)
                for o in range(1,len(mean_v1)):
                    o+=1
                    o*=-1
                    if pl-datetime.timedelta(days=7)!=datetime.datetime.fromtimestamp(mean_v1[o][0]/1000,timezone.utc):
                        print("AAAA:",o,'|',datetime.datetime.fromtimestamp(mean_v1[o][0]/1000,timezone.utc))

                    pl=datetime.datetime.fromtimestamp(mean_v1[o][0]/1000,timezone.utc)
                mean_v1=mean_v1[:,-1]
                mean_v2=np.array(ku_can_v)[:100,-1]

                k=mean_v1/mean_v2
                k=k[k!=np.inf].mean()
                ku_can=ku_can_v[100:]
                ku_can_new=[]
                for inde,o in enumerate(ku_can):
                    if inde==0:
                        o[1]=data[-1][4]
                        o[2]=max(o[2],max(o[4],o[1]))
                        o[3]=min(o[3],min(o[4],o[1]))
                    if inde+1==len(ku_can):
                        o[4]=i[1]
                        o[2]=max(o[2],max(o[4],o[1]))
                        o[3]=min(o[3],min(o[4],o[1]))
                    o[5]=o[5]*k
                    ku_can_new.append(o)

                ku_can=ku_can_new
                dot.extend(ku_can)
                dot.append(i)

            else:
                dot.append(i)
            last=datetime.datetime.fromtimestamp(i[0]/1000,datetime.timezone.utc)
        return dot

In [4]:
k=parse()
#f=k(datetime.datetime.fromisoformat("2026-05-10 03:03:04+00:00"))
#f=k(datetime.datetime.now(timezone.utc))
t=datetime.datetime.now(datetime.timezone.utc)
f=k(datetime.datetime(year=t.year,month=t.month,day=t.day,hour=t.hour,minute=15*(t.minute//15),tzinfo=datetime.timezone.utc)-datetime.timedelta(minutes=1))

print(f[0]['1w'][-20:])
print(f[0]['4h'][-20:])
print(f[0]['15m'][-20:])

11
2026-05-21 08:15:00+00:00 2
fr:1w: start:2024-06-20 07:15:00+00:00| end:2026-05-31 19:44:01+00:00
fr:4h: start:2026-05-04 15:15:00+00:00| end:2026-05-31 19:44:01+00:00
fr:15m: start:2026-05-20 06:15:00+00:00| end:2026-05-31 19:44:01+00:00
fr:1w| len:31
start:2026-05-18 00:00:00+00:00
end:2026-05-25 00:00:00+00:00
fr:4h| len:93
start:2026-05-21 04:00:00+00:00
end:2026-05-31 16:00:00+00:00
last:2026-05-20 06:15:00+00:00-end:2026-05-31 19:30:00+00:00
fr:15m| len:1040
start:2026-05-21 07:00:00+00:00
end:2026-05-31 19:30:00+00:00
                    timestamp      open      high       low     close  \
391 2026-01-12 00:00:00+00:00  91013.66  97924.49  90128.44  93673.14
392 2026-01-19 00:00:00+00:00  93673.14  93673.14  86074.72  86670.36
393 2026-01-26 00:00:00+00:00  86670.36  90600.00  75700.00  76968.21
394 2026-02-02 00:00:00+00:00  76968.22  79360.00  60000.00  70330.38
395 2026-02-09 00:00:00+00:00  70330.38  71453.53  65118.00  68832.58
396 2026-02-16 00:00:00+00:00  68832.59  70126.67  65631.83  67643.40
397 2026-02-23 00:00:00+00:00  67643.39  69988.83  62510.28  65776.47
398 2026-03-02 00:00:00+00:00  65776.48  74050.00  65259.21  65971.20
399 2026-03-09 00:00:00+00:00  65971.20  73913.74  65821.97  72815.24
400 2026-03-16 00:00:00+00:00  72815.25  76000.00  67360.66  67859.00
401 2026-03-23 00:00:00+00:00  67859.00  72026.09  65000.00  66010.93
402 2026-03-30 00:00:00+00:00  66010.93  69310.00  65712.12  69034.18
403 2026-04-06 00:00:00+00:00  69034.18  73790.00  67732.01  70740.98
404 2026-04-13 00:00:00+00:00  70741.56  78333.00  70566.99  73801.79
405 2026-04-20 00:00:00+00:00  73801.80  79472.82  73724.31  78657.55
406 2026-04-27 00:00:00+00:00  78657.55  79485.66  74937.52  78568.57
407 2026-05-04 00:00:00+00:00  78568.58  82850.00  78202.00  82210.07
408 2026-05-11 00:00:00+00:00  82210.07  82380.00  76735.16  77457.67
410 2026-05-18 00:00:00+00:00  77457.67  78200.00  74289.60  77064.96
411 2026-05-25 00:00:00+00:00  77064.96  78080.00  72512.49  73525.86

            volue        rsi        adx        bb          atr
391  106130.99963  42.212875  22.479107  0.333059  8520.496633
392  100317.13896  36.352375  22.632291  0.217675  8454.634017
393  175738.70675  30.114370  23.826408  0.076202  8915.017301
394  384283.11539  26.734307  25.981450  0.019829  9661.087494
395  163165.87355  26.024492  27.982561  0.056331  9423.547673
396  113599.38988  25.446810  29.840736  0.067266  9071.497125
397  174645.67528  24.526352  31.752096  0.076627  8957.715187
398  185435.28412  24.831770  32.705353  0.121476  8945.791960
399  173796.90567  34.815804  33.590521  0.262132  8884.790391
400  145050.61744  31.547918  33.977948  0.179626  8867.258220
401  137696.42185  30.402026  34.549431  0.161910  8735.746205
402  110218.58039  34.587767  35.080094  0.256785  8368.755761
403  121909.25954  36.895212  34.592794  0.316318  8203.701064
404  128729.92407  40.920072  33.265742  0.405314  8172.437417
405   94938.10789  46.725248  31.825111  0.539360  7999.299744
406   88811.52864  46.634819  30.484918  0.550947  7752.788334
407  113527.76932  50.828898  28.600584  0.660054  7531.017739
408   97802.77673  45.772927  27.096529  0.547497  7396.290757
410   87142.14908  44.854761  50.991659  0.562186  7213.804499
411   94442.54610  40.815102  49.473103  0.477280  7096.212035
                      timestamp      open      high       low     close  \
18390 2026-05-28 12:00:00+00:00  73505.65  73580.75  72582.82  72928.73
18391 2026-05-28 16:00:00+00:00  72928.73  73749.69  72741.40  73419.32
18392 2026-05-28 20:00:00+00:00  73419.31  73949.22  73241.48  73617.51
18393 2026-05-29 00:00:00+00:00  73617.52  73868.33  73189.11  73301.52
18394 2026-05-29 04:00:00+00:00  73301.53  73939.19  73210.21  73528.56
18395 2026-05-29 08:00:00+00:00  73528.55  73902.85  73341.85  73487.98
18396 2026-05-29 12:00:00+00:00  73487.98  74200.00  72512.49  73808.26
18397 2026-05-29 16:00:00+00:00  73808.25  74514.10  73187.25  73520.28
18398 2026-05-29 20:00:00+00:00  73520.29  73844.00  73320.00  73460.78
18399 2026-05-30 00:00:00+00:00  73460.78  73796.43  73408.62  73524.01
18400 2026-05-30 04:00:00+00:00  73524.01  73709.91  73216.00  73548.60
18401 2026-05-30 08:00:00+00:00  73548.60  73680.75  73500.02  73602.02
18402 2026-05-30 12:00:00+00:00  73602.01  74100.00  73594.40  73930.14
18403 2026-05-30 16:00:00+00:00  73930.13  74143.76  73811.30  74016.65
18404 2026-05-30 20:00:00+00:00  74016.64  74054.00  73781.30  73884.38
18405 2026-05-31 00:00:00+00:00  73884.38  74275.66  73858.56  74150.64
18406 2026-05-31 04:00:00+00:00  74150.64  74221.33  73836.00  73871.24
18407 2026-05-31 08:00:00+00:00  73871.25  74024.00  73699.20  73937.79
18408 2026-05-31 12:00:00+00:00  73937.63  74023.99  73483.05  73655.21
18409 2026-05-31 16:00:00+00:00  73655.20  73734.00  73400.00  73525.86

            volue        rsi        adx        bb         atr
18390  4632.38493  24.383135  24.693386  0.023156  830.070908
18391  2524.28664  31.136221  26.285393  0.148154  842.800843
18392  1595.41074  33.711758  27.336635  0.209573  833.153640
18393  2123.30407  31.677508  28.360690  0.186111  822.158380
18394  2641.80699  34.725275  29.146718  0.248837  815.502782
18395  2197.79295  34.429647  29.876601  0.265566  797.324011
18396  4624.93207  38.854189  31.338750  0.344071  860.908725
18397  5596.86593  36.471169  31.957761  0.305307  894.190245
18398  1502.03940  35.980157  32.532556  0.311412  867.748084
18399  1539.64276  36.951579  33.066295  0.345292  833.466792
18400  1487.87007  37.349719  33.776386  0.370608  809.212736
18401  1076.47863  38.261826  34.435755  0.404836  764.321112
18402  1485.09864  43.685076  33.902265  0.535528  745.841032
18403   836.20775  45.055480  33.293961  0.620956  716.313816
18404  1090.11124  43.319717  32.777654  0.621898  684.627115
18405  1099.56261  47.688582  31.689676  0.900070  665.518035
18406   869.39106  43.867514  30.722716  0.750299  645.504604
18407  1250.59286  44.997974  30.092681  0.781118  622.597132
18408  1349.33176  41.203487  29.911092  0.518423  616.764480
18409   893.92396  39.559056  29.892838  0.399642  596.567017
                       timestamp      open      high       low     close  \
262016 2026-05-31 14:45:00+00:00  73615.95  73699.99  73588.81  73602.17
262017 2026-05-31 15:00:00+00:00  73602.18  73682.00  73588.80  73677.18
262018 2026-05-31 15:15:00+00:00  73677.18  73775.79  73658.45  73748.67
262019 2026-05-31 15:30:00+00:00  73748.66  73754.91  73616.00  73638.46
262020 2026-05-31 15:45:00+00:00  73638.47  73681.99  73625.65  73655.21
262021 2026-05-31 16:00:00+00:00  73655.20  73730.00  73603.37  73617.58
262022 2026-05-31 16:15:00+00:00  73617.58  73629.48  73518.67  73610.36
262023 2026-05-31 16:30:00+00:00  73610.35  73610.36  73400.00  73493.97
262024 2026-05-31 16:45:00+00:00  73493.97  73544.03  73442.88  73526.14
262025 2026-05-31 17:00:00+00:00  73526.15  73556.46  73466.67  73518.00
262026 2026-05-31 17:15:00+00:00  73517.99  73598.71  73517.99  73598.32
262027 2026-05-31 17:30:00+00:00  73598.32  73724.96  73598.32  73724.96
262028 2026-05-31 17:45:00+00:00  73724.95  73734.00  73685.71  73709.44
262029 2026-05-31 18:00:00+00:00  73709.43  73713.34  73616.00  73654.00
262030 2026-05-31 18:15:00+00:00  73654.00  73680.00  73611.74  73630.21
262031 2026-05-31 18:30:00+00:00  73630.21  73708.80  73630.21  73642.72
262032 2026-05-31 18:45:00+00:00  73642.71  73642.72  73585.49  73603.69
262033 2026-05-31 19:00:00+00:00  73603.68  73649.93  73590.38  73590.39
262034 2026-05-31 19:15:00+00:00  73590.38  73618.93  73457.09  73526.00
262035 2026-05-31 19:30:00+00:00  73526.00  73543.82  73456.48  73520.41

            volue        rsi        adx        bb         atr
262016   57.56015  30.374587  27.132601 -0.015212  110.889705
262017   48.78077  37.579169  29.224984  0.171192  109.626154
262018   65.58614  43.572180  29.600472  0.316742  110.177143
262019   61.34570  37.581811  30.248658  0.145553  112.229490
262020   91.22038  38.955441  30.850545  0.207366  108.237384
262021   82.12775  36.986184  30.642297  0.178568  109.551142
262022   59.81865  36.603845  31.109192  0.198795  109.641060
262023  141.06530  31.034362  32.270364  0.065056  116.835270
262024   36.74255  34.022523  33.348594  0.156190  115.714894
262025   55.19179  33.625516  34.146467  0.179179  113.863116
262026   25.84532  40.947878  34.205604  0.323593  111.495750
262027   57.73269  50.264318  32.570674  0.549420  112.577483
262028   56.69994  49.239068  30.946490  0.543590  107.985519
262029   50.05428  45.656543  30.080467  0.464576  107.225125
262030   67.39184  44.171373  29.314102  0.439805  104.441902
262031   44.89382  45.181207  28.216200  0.502369  102.595338
262032   52.03080  42.592672  27.629663  0.406800   99.354956
262033   38.66906  41.715606  26.981462  0.375513   96.511745
262034   42.49804  37.671167  27.507518  0.149175  101.178049
262035   61.24794  37.332769  28.000476  0.163399  100.189617

In [102]:
print(pd.read_feather(path_f4))
a=pd.read_parquet(path4_,engine='pyarrow')
print(a[-5:])

                      timestamp     open      high       low     close  \
18323 2026-05-17 08:00:00+00:00  78180.0  78293.97  78033.01  78260.56

           volue        rsi       adx        bb         atr
18323  320.75537  36.803991  36.28848  0.269597  668.089959
                      timestamp      open      high       low     close  \
18318 2026-05-16 16:00:00+00:00  78238.68  78364.65  78119.72  78259.66
18319 2026-05-16 20:00:00+00:00  78259.67  78318.94  78125.32  78148.05
18320 2026-05-17 00:00:00+00:00  78148.05  78243.19  77721.19  78028.88
18321 2026-05-17 04:00:00+00:00  78028.88  78323.96  78003.35  78180.01
18322 2026-05-17 08:00:00+00:00  78180.00  78293.97  78033.01  78270.39

            volue        rsi        adx        bb         atr
18318  1260.04581  36.181338  28.979766  0.189530  766.951752
18319   689.34644  35.418209  30.065280  0.181398  725.999484
18320  1284.92928  34.579558  31.420590  0.186406  711.428093
18321   952.09545  36.628900  32.483172  0.239450  683.512515
18322   306.17476  37.882110  33.469855  0.271453  653.330192

In [ ]:
dups = f[0]['4h'].duplicated(subset='timestamp', keep='last')
print(dups.to_string())

In [17]:
a=pd.read_parquet(path15,engine='pyarrow')
a.to_parquet(path15_,engine='pyarrow')
a=pd.read_parquet(path1,engine='pyarrow')
a.to_parquet(path1_,engine='pyarrow')
a=pd.read_parquet(path4,engine='pyarrow')
a.to_parquet(path4_,engine='pyarrow')
path_f15=Path(r'D:\Python1\AI\cripto_bot\from_3_3.feather')
path_f4=Path(r'D:\Python1\AI\cripto_bot\from_2_3.feather')
path_f1=Path(r'D:\Python1\AI\cripto_bot\from_1_3.feather')
pd.DataFrame([]).to_feather(path_f15)
pd.DataFrame([]).to_feather(path_f4)
pd.DataFrame([]).to_feather(path_f1)

In [3]:
print('-------------15m--------------')
path15=r'D:\Python1\AI\cripto_bot\from_3_3.parquet'
path15_=r'D:\Python1\AI\cripto_bot\from_3_4.parquet'
path15_1=r"D:\Python1\AI\cripto_bot\test_data\from_3_4.parquet"

path4=r"D:\Python1\AI\cripto_bot\from_2_3.parquet"
path4_=r"D:\Python1\AI\cripto_bot\from_2_4.parquet"

path1=r"D:\Python1\AI\cripto_bot\from_1_3.parquet"
path1_=r"D:\Python1\AI\cripto_bot\from_1_4.parquet"

f=({'15m':pd.read_parquet(path15_1),'4h':pd.read_parquet(path4_),'1w':pd.read_parquet(path1_)},)
m15=f[0]['15m']["timestamp"]
start=m15.iloc[0]
print('start:',start)

print("end:",m15.iloc[-1])
for i,sv in enumerate(m15):
    tim=m15.iloc[i]
    if tim!=start:
        print('----------------------------')
        print(f"error:{start} != {tim}",'i:',i)
        start=tim

    start=datetime.timedelta(minutes=15)+start
print(len(m15))

print('-------------4h--------------')
m15=f[0]['4h']["timestamp"]
start=m15.iloc[0]
print('start:',start)

print("end:",m15.iloc[-1])
for i,sv in enumerate(m15):
    tim=m15.iloc[i]
    if tim!=start:
        print('----------------------------')
        print(f"error:{start} != {tim}",'i:',i)
        start=tim

    start=datetime.timedelta(hours=4)+start
print(len(m15))
print('-------------1w--------------')

m15=f[0]['1w']["timestamp"]
start=m15.iloc[0]
print('start:',start)

print("end:",m15.iloc[-1])
for i,sv in enumerate(m15):
    tim=m15.iloc[i]
    if tim!=start:
        print('----------------------------')
        print(f"error:{start} != {tim}",'i:',i)
        start=tim

    start=datetime.timedelta(days=7)+start
print(len(m15))

-------------15m--------------
start: 2018-12-10 06:45:00+00:00
end: 2026-05-21 10:45:00+00:00
261041
-------------4h--------------
start: 2018-01-05 16:00:00+00:00
end: 2026-05-21 04:00:00+00:00
18346
-------------1w--------------
start: 2018-07-16 00:00:00+00:00
end: 2026-05-18 00:00:00+00:00
410

In [ ]:
m15.iloc[17650:17660]

In [6]:
import pandas as pd
from pathlib import Path
path15=r'D:\Python1\AI\cripto_bot\from_3_3.parquet'
path15_=r'D:\Python1\AI\cripto_bot\from_3_4.parquet'
path15_1=r"D:\Python1\AI\cripto_bot\test_data\from_3_4.parquet"

path4=r"D:\Python1\AI\cripto_bot\from_2_3.parquet"
path4_=r"D:\Python1\AI\cripto_bot\from_2_4.parquet"

path1=r"D:\Python1\AI\cripto_bot\from_1_3.parquet"
path1_=r"D:\Python1\AI\cripto_bot\from_1_4.parquet"

path_f15=Path(r'D:\Python1\AI\cripto_bot\from_3_3.feather')

path_f4=Path(r'D:\Python1\AI\cripto_bot\from_2_3.feather')
path_f1=Path(r'D:\Python1\AI\cripto_bot\from_1_3.feather')
a=pd.read_parquet(path15_)
print(pd.read_feather(path_f15))
a[-30:]

Empty DataFrame
Columns: []
Index: []

,timestamp,open,high,low,close,volue,rsi,adx,bb,atr
262006,2026-05-31 12:15:00+00:00,73918.00,73995.88,73917.99,73933.21,44.94484,49.094817,18.595520,0.633838,83.091930
262007,2026-05-31 12:30:00+00:00,73933.21,73974.89,73906.00,73974.89,85.90487,52.761733,18.445486,0.809061,82.077507
262008,2026-05-31 12:45:00+00:00,73974.88,73979.23,73880.00,73920.00,45.87031,47.871125,18.636592,0.525018,83.302685
262009,2026-05-31 13:00:00+00:00,73920.00,73957.04,73880.00,73948.21,36.63870,50.414960,18.814046,0.655422,82.855350
262010,2026-05-31 13:15:00+00:00,73948.21,74023.99,73936.00,73961.16,31.66868,51.583006,17.750723,0.727754,83.222111
262011,2026-05-31 13:30:00+00:00,73961.17,73971.68,73887.63,73896.64,30.01315,45.794911,17.445890,0.397563,83.281246
262012,2026-05-31 13:45:00+00:00,73896.64,73900.33,73807.43,73872.80,80.12681,43.837546,18.094827,0.295166,83.968300
262013,2026-05-31 14:00:00+00:00,73872.80,73872.80,73670.08,73719.41,191.23763,33.821026,19.839434,-0.211731,92.450564
262014,2026-05-31 14:15:00+00:00,73719.40,73783.17,73483.05,73582.78,297.03268,27.740759,22.452708,-0.301665,107.284095
262015,2026-05-31 14:30:00+00:00,73582.79,73740.23,73582.78,73615.95,135.89445,30.984645,24.879319,-0.079657,110.867374
262016,2026-05-31 14:45:00+00:00,73615.95,73699.99,73588.81,73602.17,57.56015,30.374587,27.132601,-0.015212,110.889705
262017,2026-05-31 15:00:00+00:00,73602.18,73682.00,73588.80,73677.18,48.78077,37.579169,29.224984,0.171192,109.626154
262018,2026-05-31 15:15:00+00:00,73677.18,73775.79,73658.45,73748.67,65.58614,43.572180,29.600472,0.316742,110.177143
262019,2026-05-31 15:30:00+00:00,73748.66,73754.91,73616.00,73638.46,61.34570,37.581811,30.248658,0.145553,112.229490
262020,2026-05-31 15:45:00+00:00,73638.47,73681.99,73625.65,73655.21,91.22038,38.955441,30.850545,0.207366,108.237384
262021,2026-05-31 16:00:00+00:00,73655.20,73730.00,73603.37,73617.58,82.12775,36.986184,30.642297,0.178568,109.551142
262022,2026-05-31 16:15:00+00:00,73617.58,73629.48,73518.67,73610.36,59.81865,36.603845,31.109192,0.198795,109.641060
262023,2026-05-31 16:30:00+00:00,73610.35,73610.36,73400.00,73493.97,141.06530,31.034362,32.270364,0.065056,116.835270
262024,2026-05-31 16:45:00+00:00,73493.97,73544.03,73442.88,73526.14,36.74255,34.022523,33.348594,0.156190,115.714894
262025,2026-05-31 17:00:00+00:00,73526.15,73556.46,73466.67,73518.00,55.19179,33.625516,34.146467,0.179179,113.863116
262026,2026-05-31 17:15:00+00:00,73517.99,73598.71,73517.99,73598.32,25.84532,40.947878,34.205604,0.323593,111.495750
262027,2026-05-31 17:30:00+00:00,73598.32,73724.96,73598.32,73724.96,57.73269,50.264318,32.570674,0.549420,112.577483
262028,2026-05-31 17:45:00+00:00,73724.95,73734.00,73685.71,73709.44,56.69994,49.239068,30.946490,0.543590,107.985519
262029,2026-05-31 18:00:00+00:00,73709.43,73713.34,73616.00,73654.00,50.05428,45.656543,30.080467,0.464576,107.225125
262030,2026-05-31 18:15:00+00:00,73654.00,73680.00,73611.74,73630.21,67.39184,44.171373,29.314102,0.439805,104.441902
262031,2026-05-31 18:30:00+00:00,73630.21,73708.80,73630.21,73642.72,44.89382,45.181207,28.216200,0.502369,102.595338
262032,2026-05-31 18:45:00+00:00,73642.71,73642.72,73585.49,73603.69,52.03080,42.592672,27.629663,0.406800,99.354956
262033,2026-05-31 19:00:00+00:00,73603.68,73649.93,73590.38,73590.39,38.66906,41.715606,26.981462,0.375513,96.511745
262034,2026-05-31 19:15:00+00:00,73590.38,73618.93,73457.09,73526.00,42.49804,37.671167,27.507518,0.149175,101.178049
262035,2026-05-31 19:30:00+00:00,73526.00,73543.82,73456.48,73520.41,61.24794,37.332769,28.000476,0.163399,100.189617

In [4]:
path15=r'D:\Python1\AI\cripto_bot\from_3_3.parquet'
path15_=r'D:\Python1\AI\cripto_bot\from_3_4.parquet'

path4=r"D:\Python1\AI\cripto_bot\from_2_3.parquet"
path4_=r"D:\Python1\AI\cripto_bot\from_2_4.parquet"

path1=r"D:\Python1\AI\cripto_bot\from_1_3.parquet"
path1_=r"D:\Python1\AI\cripto_bot\from_1_4.parquet"
pd.DataFrame([]).to_feather(path_f15)
pd.DataFrame([]).to_feather(path_f4)
pd.DataFrame([]).to_feather(path_f1)